version: "3.7"
services:
    app:
        build:
            args:
                user: raul
                uid: 1000
                NODE_ENV: production
            context: ./
            dockerfile: Dockerfile
        image: market
        container_name: market-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - market
    db:
        image: mysql:8.0
        container_name: market-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - market
    nginx:
        image: nginx:1.17-alpine
        container_name: market-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - market
    node:
        image: node:latest
        container_name: market-node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - market
networks:
    market:
        driver: bridge

volumes:
    mysql-data:
